language: ruby
rvm:
  - ruby-2.1.1
script:
  - bundle install --deployment
  - gem install brakeman
  - brakeman -q -z
  - bundle exec rake
notifications:
  slack: cfa:KVI8UW1LayfvwbSb5i52Rqb6#charlotte
